### ISSUE TITLE
Error: Request failed with status code 401

### ISSUE THREAD

**Issue by matheozz** [DevSamurai/food-gpt#4]
apenas importei a lib, comprei alguns tokens no gpt e alterei a key, não fiz alterações no codigo

estou recebendo o seguinte erro ao receber qualquer mensagem
alguém por favor sabe a solução? 
grato

```
+556296298848 👤 oi
Error: Request failed with status code 401
    at createError (C:\Users\mathg\Desktop\food-gpt-main\node_modules\openai\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\mathg\Desktop\food-gpt-main\node_modules\openai\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\mathg\Desktop\food-gpt-main\node_modules\openai\node_modules\axios\lib\adapters\http.js:322:11)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'OpenAI/NodeJS/3.3.0',
      Authorization: 'Bearer undefined',
      'Content-Length': 7485
    },
    method: 'post',
    data: '{"model""gpt-3.5-turbo","temperature":0,"max_tokens":256,"messages":[{"role":"system","content": ROTEIRO....

```

**Comment by deviego** [comment]
esse erro significa que a sua chave token não está sendo reconhecida, no aruivo de openia importa o dotenv e da um dotenv.config() e irá funcionar
